version: "3.3"

services:
  node:
    build: ./node/
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "C:\\Users\\abida\\OneDrive\\Área de Trabalho\\projetos\\test-node\\node:/app"
    networks:
      - dockercompose

networks:
  dockercompose:
